/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

const imagesConstants = {
  // intro1: require('../assets/images/intro1.jpeg'),
  // intro2: require('../assets/images/intro2.jpeg'),
  // intro3: require('../assets/images/intro3.jpeg'),
  intro1: require('../assets/images/Slide-01.jpg'),
  intro2: require('../assets/images/Slide-02.jpg'),
  intro3: require('../assets/images/Slide-03.jpg'),
  intro4: require('../assets/images/Slide-04.jpg'),
  // intro5: require('../assets/images/Slide-05.jpg'),

  placeholder: require('../assets/images/placeholder.png'),
  inactiveHome: require('../assets/images/inactiveHome.png'),
  inactiveSearch: require('../assets/images/inactiveSearch.png'),
  inactiveCall: require('../assets/images/inactiveCallUs.png'),
  inactiveMyAccount: require('../assets/images/inactiveMyAccount.png'),
  activeHome: require('../assets/images/activeHome.png'),
  activeSearch: require('../assets/images/activeSearch.png'),
  activeCall: require('../assets/images/activeCall.png'),
  activeMyAccount: require('../assets/images/activeMyAccount.png'),
  activeNeedHelp: require('../assets/images/help_active.png'),
  inactiveNeedHelp: require('../assets/images/help.png'),
  lungs: require('../assets/images/lungs.png'),
  noReports: require('../assets/images/reports.png'),
  reports: require('../assets/images/reports.png'),
  browseLabTest: require('../assets/images/browseLabTest.png'),
  whiteLocationPin: require('../assets/images/whiteLocationPin.png'),
  pharmacy: require('../assets/images/pharmacy.png'),
  uploadprescription: require('../assets/images/uploadprescription.png'),
  cart: require('../assets/images/cart.png'),
  newsImage: require('../assets/images/newsImage.png'),
  bell: require('../assets/images/bell.png'),
  notiBell: require('../assets/images/notiBell.png'),
  search: require('../assets/images/search.png'),
  award: require('../assets/images/award.png'),
  termsCheck: require('../assets/images/termsCheck.png'),
  whitepin: require('../assets/images/whitepin.png'),
  menu: require('../assets/images/menu.png'),
  del: require('../assets/images/del.png'),
  eid: require('../assets/images/edi.png'),
  direction: require('../assets/images/direction.png'),
  men: require('../assets/images/men.png'),
  locationOff: require('../assets/images/locationOff.png'),
  calendar: require('../assets/images/calendar.png'),
  facalities: require('../assets/images/facalities.png'),
  call: require('../assets/images/call.png'),
  filter: require('../assets/images/filter.png'),
  tick: require('../assets/images/tick.png'),
  cancelRed: require('../assets/images/redCancel.png'),
  male: require('../assets/images/male.png'),
  mandf: require('../assets/images/mandf.png'),
  female: require('../assets/images/female.png'),
  test: require('../assets/images/test.png'),
  people: require('../assets/images/people.png'),
  rep: require('../assets/images/rep.png'),
  timer: require('../assets/images/timer.png'),
  uparrow: require('../assets/images/uparrow.png'),
  downarrow: require('../assets/images/downarrow.png'),
  arrowRight: require('../assets/images/arrowRight.png'),
  drawerArrow: require('../assets/images/drawerArrow.png'),
  pdf: require('../assets/images/pdf.png'),
  flask: require('../assets/images/flask.png'),
  house: require('../assets/images/house.png'),
  office: require('../assets/images/office.png'),
  other: require('../assets/images/others.png'),
  blalLogo: require('../assets/images/blallablogo.png'),
  backWhite: require('../assets/images/backWhite.png'),
  whiteBackground: require('../assets/images/background.png'),
  backGreen: require('../assets/images/greenBackArrow.png'),
  blankcircle: require('../assets/images/blankcircle.png'),
  selectedcircle: require('../assets/images/selectedcircel.png'),
  camera: require('../assets/images/camera.png'),
  info: require('../assets/images/info.png'),
  edit: require('../assets/images/edit.png'),
  booking_success: require('../assets/images/booking_success.png'),
  location: require('../assets/images/location.png'),
  mylocation: require('../assets/images/mylocation.png'),
  add_plus: require('../assets/images/add.png'),
  emptyCartImage: require('../assets/images/emptyCartImage.jpg'),
  phoneCallUs: require('../assets/images/phone-call-us.png'),
  download: require('../assets/images/download.png'),
  graph: require('../assets/images/graph.png'),
  infoPre: require('../assets/images/infopre.png'),
  bookingConfirmed: require('../assets/images/01.png'),
  proAssign: require('../assets/images/02.png'),
  started: require('../assets/images/03.png'),

  sameType: require('../assets/images/samType.png'),
  iconMale: require('../assets/images/iconMale.png'),
  femaleIcon: require('../assets/images/femaleIcon.png'),

  collectionDone: require('../assets/images/04.png'),

  sampleAtLab: require('../assets/images/05.png'),
  reportApproved: require('../assets/images/06.png'),
  testCorner: require('../assets/images/testCorner.png'),
  packageCorner: require('../assets/images/packageCorner.png'),

  share: require('../assets/images/share.png'),
  like: require('../assets/images/like.png'),
  comment: require('../assets/images/comment.png'),

  labtool: require('../assets/images/labtool.png'),
  trackPro: require('../assets/images/trackPro.png'),
  callBooking: require('../assets/images/callBooking.png'),

  point: require('../assets/images/point.png'),
  marker: require('../assets/images/marker.png'),

  tracking: require('../assets/images/trackingImg.png'),
};

export default imagesConstants;
