require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'blal' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'blalTests' do
    inherit! :complete
   
  end

 
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
  
end
