export const TOKEN = 'TOKEN';
export const PROFILE_SETUP = 'PROFILE_SETUP';
export const BUSINESS_TOKEN = 'BUSINESS_TOKEN';
export const PROFILE_SETUP_BUSINESS = 'PROFILE_SETUP_BUSINESS';
export const BUSINESS_USER = 'BUSINESS_USER';
export const IS_BUSINESS_USER_LOGGEDOUT = 'IS_BUSINESS_USER_LOGGEDOUT';
